# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r2GXDYlr4aMcSsy-ODvD3W5ga38AIVvD
"""

import pandas as pd
baza ={
    "Fish":[ "Mirzahamidov Jaloliddin" ,"Mirzahamidova Marjona ", "Mirzahamidov Davronbek","Mirzahamidov Mustafo","Mirzahamidova"   ],
    "Yoshi":[  "20","18", "21" ,"12", ],
    "Maktabi":[     "19-maktab","19-maktab","19-maktab","19-maktab", ],
    "Jinsi":[     "o'g'il bola", "qiz bola", "o'g'il bola","o'g'il  bola" ,  ],
    "Manzili":[    "Farg'ona shahar", "Qo'qon shahar", "Farg'ona shahar","Qo'qon shahar",  ]
}
db=pd.DataFrame(baza)
print(db)

filtr=[db['Jinsi']=="o'g'il bola"]
  print(fdbiltr)

filtr=db[(db['Jinsi']=="qiz bola")& (db['Manzili']=="Qo'qon shahar" )]
  print(filtr)